#Social/Personal Service Information 
consumer_key_twitter=''
consumer_secret_twitter=''
access_token_twitter=''
access_token_secret_twitter=''
app_id_facebook=''
app_secret_facebook=''
sms_sender=''
sms_sender_pass=''
sms_recipient_number=''
sms_recipient_email=''
